@Library('EZJEL') _

def dockerImage
pipeline {
    agent {
        kubernetes {
        label 'aquavue'
        idleMinutes 5
        yamlFile 'build-pod.yaml'
        defaultContainer 'aquavue-docker-helm-build'
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    environment {
        DOCKER_IMAGE = 'idosxd/aquavue'
        HELM_PACKAGE = 'idosxd/aquavue-chart'
    }

    stages {
        stage('Setup') {
            steps {
                checkout scm
                script {
                    ezEnvSetup.initEnv()
                    def id = ezUtils.getUniqueBuildIdentifier()
                    if(BRANCH_NAME == 'main')
                    {
                        env.BUILD_ID = "1."+id
                    }
                    else {
                        env.BUILD_ID = "0." + ezUtils.getUniqueBuildIdentifier("issueNumber") + "." + id
                    }
                    currentBuild.displayName+=" {build-name:"+env.BUILD_ID+"}"
                }
            }
        }

        stage('Build Docker image') {
            steps {
                script {
                    dockerImage = docker.build(DOCKER_IMAGE+":"+env.BUILD_ID,"--no-cache .")
                }
            }
        }

        stage('Build Helm Chart') {
            steps {
                sh 'helm lint aquavue-chart'
                sh 'helm package aquavue-chart --version '+env.BUILD_ID
            }
        }

        stage('Push Docker image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'idosxd_dockerhub_credentials') {
                        dockerImage.push()
                    }
                }
            }
        }

        stage('Push HELM chart') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'idosxd_dockerhub_credentials', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USER')]) {
                        sh "docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}"
                        sh 'helm push aquavue-chart-'+env.BUILD_ID+'.tgz oci://registry-1.docker.io/idosxd'
                    }
                }
            }
        }
    }
}
