apiVersion: v1
kind: Service
metadata:
  name: aquavue
  labels:
    app: aquavue
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
  selector:
    app: aquavue
